const config = {
    TILE_SIZE: 16,  // in pixels
    MOVEMENT_ANIMDURATION: 900, // in milliseconds
    API_PROTOCOL: 'ENV_API_PROTOCOL',
    API_DOMAIN: 'ENV_API_DOMAIN',
    API_PORT: 'ENV_API_PORT',
    LRS_ENDPOINT: 'ENV_LRS_ENDPOINT',
    LRS_USERNAME: 'ENV_LRS_USERNAME',
    LRS_PASSWORD: 'ENV_LRS_PASSWORD',
    GAME_VERSION: 'ENV_GAME_VERSION',
    EDITOR_MIN_ROWS: 3,
    EDITOR_MIN_COLS: 3,
    EDITOR_MAX_ROWS: 15,
    EDITOR_MAX_COLS: 15,
};

export default config;